#!/bin/bash
# TunnelSats for StartOS - Entrypoint Script
# Parses WireGuard config, starts tunnel, SOCKS5 proxy, and inbound forwarder

set -euo pipefail

# ============================================
# Configuration
# ============================================
CONFIG_FILE="/data/tunnelsats.conf"
WG_CONF="/etc/wireguard/ts0.conf"
SOCKS_PORT="${SOCKS_PORT:-9050}"
LND_HOST="${LND_HOST:-lnd.embassy}"
LND_PORT="${LND_PORT:-9735}"

# ============================================
# Logging helpers
# ============================================
log_info() { echo "[TunnelSats] $1"; }
log_error() { echo "[TunnelSats ERROR] $1" >&2; }
log_success() { echo "[TunnelSats ✓] $1"; }

# ============================================
# Config Parser Functions
# ============================================
parse_field() {
    local field="$1"
    grep -oP "${field}"' *= *\K.*' "$CONFIG_FILE" 2>/dev/null | head -1 || echo ""
}

parse_comment() {
    local field="$1"
    grep -oP "# ${field}: *\K.*" "$CONFIG_FILE" 2>/dev/null | head -1 || echo ""
}

# ============================================
# Main Logic
# ============================================
main() {
    log_info "Starting TunnelSats v0.1.0..."

    # Check config file exists
    if [[ ! -f "$CONFIG_FILE" ]]; then
        log_error "Config file not found at $CONFIG_FILE"
        log_error "Please paste your TunnelSats WireGuard configuration in the service config."
        exit 1
    fi

    # Parse WireGuard config
    log_info "Parsing WireGuard configuration..."
    
    PRIVATE_KEY=$(parse_field "PrivateKey")
    ADDRESS=$(parse_field "Address")
    PEER_PUBKEY=$(parse_field "PublicKey")
    PRESHARED_KEY=$(parse_field "PresharedKey")
    ENDPOINT=$(parse_field "Endpoint")
    ALLOWED_IPS=$(parse_field "AllowedIPs")
    
    # Parse TunnelSats metadata from comments
    VPN_PORT=$(parse_comment "Port Forwarding")
    VPN_SERVER=$(parse_comment "Server")
    VALID_UNTIL=$(parse_comment "Valid Until")
    MY_PUBKEY=$(parse_comment "myPubKey")

    # Validate required fields
    local missing=0
    [[ -z "$PRIVATE_KEY" ]] && { log_error "Missing: PrivateKey"; missing=1; }
    [[ -z "$ADDRESS" ]] && { log_error "Missing: Address"; missing=1; }
    [[ -z "$PEER_PUBKEY" ]] && { log_error "Missing: PublicKey"; missing=1; }
    [[ -z "$ENDPOINT" ]] && { log_error "Missing: Endpoint"; missing=1; }
    
    if [[ $missing -eq 1 ]]; then
        log_error "Invalid configuration. Please check your TunnelSats config file."
        exit 1
    fi

    log_success "Config parsed successfully"
    log_info "  Server: ${VPN_SERVER:-unknown}"
    log_info "  VPN Port: ${VPN_PORT:-not configured}"
    log_info "  Valid Until: ${VALID_UNTIL:-unknown}"
    log_info "  Your Public Key: ${MY_PUBKEY:-unknown}"

    # Generate WireGuard config file
    log_info "Generating WireGuard config..."
    mkdir -p /etc/wireguard
    
    cat > "$WG_CONF" <<EOF
# Generated by TunnelSats for StartOS
# Do not edit manually

[Interface]
PrivateKey = ${PRIVATE_KEY}
Address = ${ADDRESS}
DNS = 1.1.1.1

[Peer]
PublicKey = ${PEER_PUBKEY}
${PRESHARED_KEY:+PresharedKey = ${PRESHARED_KEY}}
Endpoint = ${ENDPOINT}
AllowedIPs = ${ALLOWED_IPS:-0.0.0.0/0}
PersistentKeepalive = 25
EOF

    chmod 600 "$WG_CONF"
    log_success "WireGuard config written to $WG_CONF"

    # Start WireGuard tunnel
    log_info "Starting WireGuard tunnel (ts0)..."
    wg-quick up ts0
    
    log_success "WireGuard tunnel active"
    wg show ts0

    # Start inbound port forwarding if VPN port is configured
    if [[ -n "$VPN_PORT" ]]; then
        log_info "Starting inbound forwarder: port ${VPN_PORT} -> ${LND_HOST}:${LND_PORT}"
        socat TCP-LISTEN:${VPN_PORT},bind=0.0.0.0,reuseaddr,fork TCP:${LND_HOST}:${LND_PORT} &
        log_success "Inbound forwarder started"
    else
        log_info "No VPN port configured - skipping inbound forwarder"
    fi

    # Start SOCKS5 proxy
    log_info "Starting SOCKS5 proxy on port ${SOCKS_PORT}..."
    log_success "TunnelSats ready! Services can connect via tunnelsats.embassy:${SOCKS_PORT}"
    
    # exec replaces this process with microsocks
    exec microsocks -i 0.0.0.0 -p "${SOCKS_PORT}"
}

# Run main
main "$@"
