name: Release StartOS Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release StartOS Package
    uses: Start9Labs/start-technologies/.github/workflows/release.yml@be6d7dc7613bb7a7abe1d2318ba1d233cdef725e # master
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY || secrets.STARTOS_DEVELOPER_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
