name: Release StartOS Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release StartOS Package
    uses: Start9Labs/start-technologies/.github/workflows/release.yml@f7dcde71be804af424350b48c8b73aba03f41321 # master
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY || secrets.STARTOS_DEVELOPER_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
