name: Tag and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-and-release:
    name: Tag and Release
    uses: Start9Labs/start-technologies/.github/workflows/tagAndRelease.yml@7824e4169ef7dbc7413d076855ea20f2e77be1a2 # master
    with:
      REFERENCE_REGISTRY: 'https://community-registry.start9.com'
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY || secrets.STARTOS_DEVELOPER_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
